In [1]:
print("dfhubdefi")

dfhubdefi


First we'll convert the text data into Embedding by calling the Euri Api's text embedding model

In [15]:
import requests
import numpy as np

def generate_embeddings(text):
    url = "https://api.euron.one/api/v1/euri/alpha/embeddings"
    headers = {
        "Content-Type": "application/json",
        "Authorization": "Bearer euri-5ecfb5f7c1ad275ca925fa79e9d74e24a291fa874d025f40494fb439e4682976"
    }
    payload = {
        "input": text,
        "model": "text-embedding-3-small"
    }

    response = requests.post(url, headers=headers, json=payload)
    data = response.json()
    
    embedding = np.array(data['data'][0]['embedding'])
    
    return embedding

text = input("enter The text")

embedding1 = generate_embeddings(text)
# print(embedding)

In [ ]:
# embedding
# Today is a sunny day so I can go play cricket

(array([ 0.03411809, -0.02788874,  0.00071066, ..., -0.015417  ,
        -0.02317111,  0.00667896]),
 (1536,))

Now we'll store this vector embedding in a vector database like Chroma db, FAISS, Pinecone etc

In [10]:
text2="I coud have played football if it was a rainy day"

In [17]:
embedding2= generate_embeddings(text2)

In [12]:
import numpy as np

In [18]:
embedding1,embedding2

(array([-0.00315446, -0.00728609,  0.0191007 , ..., -0.00886728,
         0.01372467,  0.0310418 ]),
 array([-0.03650862,  0.0014237 , -0.04032449, ..., -0.03060433,
         0.0104872 ,  0.02473871]))

In [20]:
cosine_similarity=np.dot(embedding1,embedding2)/np.linalg.norm(embedding1)*np.linalg.norm(embedding2)

In [21]:
cosine_similarity

np.float64(0.4895488001883267)

In [22]:
embedding3=generate_embeddings("I like to play cricket")

In [23]:
cosine_similarity_1_3=np.dot(embedding1,embedding3)/np.linalg.norm(embedding1)*np.linalg.norm(embedding3)

In [24]:
cosine_similarity_1_3

np.float64(0.6194139652461012)

In [25]:
cosine_similarity_2_3=np.dot(embedding3,embedding2)/np.linalg.norm(embedding3)*np.linalg.norm(embedding2)

In [26]:
cosine_similarity_2_3

np.float64(0.39554286938862093)

In [28]:
cosine_distance_1_2=1-cosine_similarity
cosine_distance_1_3=1-cosine_similarity_1_3
cosine_distance_2_3=1-cosine_similarity_2_3


In [29]:
print(cosine_distance_1_2,cosine_distance_1_3,cosine_similarity_2_3)

0.5104511998116733 0.38058603475389885 0.39554286938862093
