In [135]:
print("Hello WOrld")

Hello WOrld


In [136]:
input=[1,2,3,4,5]
output=[1,6,9,12,15]

# let's just create a neural network which will understand relationship between input and output

In [137]:
# Raw python coding we won't use any library 
w=0.0  #Weight
b=0.0  #bias
lr=0.01 #learning rate

In [138]:
# we'll sending the data multiple times(epochs) in order to make th nn learn and minimizes it's losses 
for epoch in range(100):
    total_loss=0
    for x,y in zip(input,output):
        y_pred=w*x+b
        error=y_pred-y
        loss=error**2
        total_loss=total_loss+loss
        
        dw=2*error*x
        db=2*error 
        
        w=w-lr*dw 
        b=b-lr*db 
        
    if epoch %10 ==0:
        print(f"epoch {epoch} | Loss: {total_loss} | w: {w}, b: {b}")
        
test_data=6
prediction= w*test_data + b
print(prediction)
        
        
    

epoch 0 | Loss: 231.45170394306533 | w: 2.173052208, b: 0.6215089056
epoch 10 | Loss: 5.668672588717118 | w: 2.8831453346293396, b: 0.4328000726718697
epoch 20 | Loss: 4.5072196735718535 | w: 2.9577824028574384, b: 0.11635075469188232
epoch 30 | Loss: 3.696638259205255 | w: 3.0200952269251204, b: -0.14784644018673837
epoch 40 | Loss: 3.1307926739743976 | w: 3.0721189456769076, b: -0.36841934419219613
epoch 50 | Loss: 2.7356743667314647 | w: 3.1155524981319815, b: -0.5525712084985134
epoch 60 | Loss: 2.45967438653243 | w: 3.1518142941767495, b: -0.7063158820811455
epoch 70 | Loss: 2.2668006775972156 | w: 3.1820885355884427, b: -0.8346742060333362
epoch 80 | Loss: 2.131949736753241 | w: 3.2073638885224773, b: -0.941837979215763
epoch 90 | Loss: 2.0376103158588044 | w: 3.2284657703913733, b: -1.0313068498670508
18.367641995895795


In [139]:
# //creating a hidden layer 

input=[1,2,3,4,5]
output=[2,4,6,8,10]


In [140]:
w1,b1=0.1,0.0
w2,b2=-0.1,0.0
w3,w4=0.1,0.1
b3=0.0
lr=0.01

In [141]:
def relu(x):
    return max(0,x)

In [142]:
def relu_derivative(x):
    return 1 if x>0 else 0

In [143]:
for epoch in range(100):
    total_loss=0
    for x,y in zip(input,output):
        z1=w1*x+b1
        h1=relu(z1)
        
        z2=w2*x+b2
        h2=relu(z2)
        
        Y_pred=w3*h1+w4*h2+b3
        
        error=Y_pred-y
        loss=error**2
        
        total_loss =total_loss+loss
        
        dl_dy=2*error 
        dw3=dl_dy*h1
        dw4=dl_dy*h2
        db3=dl_dy
        
        dh1=dl_dy*w3
        dh2=dl_dy*w4 
        
        dz1=dh1*relu_derivative(z1)
        dz2=dh2* relu_derivative(z2)
        
        dw1=dz1*x
        db1=dz1
        
        dw2=dz2*x
        db2=dz2
        
        w1=w1-lr*dw1
        w2=w2-lr*dw2
        w3=w3-lr*dw3 
        w4=w4-lr*dw4
        
        b1=b1-lr*db1
        b2=b2-lr*db2
        b3=b3-lr*db3
        
        if epoch %10 ==0:
            print(f"epoch {epoch} | Loss: {total_loss}")
        
def prediction(x):
    z1=w1*x+b1
    h1=relu(z1)
        
    z2=w2*x+b2
    h2=relu(z2)
        
    y_=w3*h1+w4*h2+b3
    
    return y_

prediction(9)
    
        
        
        

epoch 0 | Loss: 3.9601
epoch 0 | Loss: 19.46922370942816
epoch 0 | Loss: 53.53273834591123
epoch 0 | Loss: 112.10975583145009
epoch 0 | Loss: 197.58784675778605
epoch 10 | Loss: 0.5175232634239522
epoch 10 | Loss: 0.6942119098593943
epoch 10 | Loss: 0.6943375660628105
epoch 10 | Loss: 0.7625240158039989
epoch 10 | Loss: 0.7822743866736906
epoch 20 | Loss: 0.18338824616234467
epoch 20 | Loss: 0.247170461131674
epoch 20 | Loss: 0.24722758471479223
epoch 20 | Loss: 0.27172136468731856
epoch 20 | Loss: 0.2777331306080438
epoch 30 | Loss: 0.06231414130691843
epoch 30 | Loss: 0.08415886646822263
epoch 30 | Loss: 0.0841787475443425
epoch 30 | Loss: 0.09258025509069169
epoch 30 | Loss: 0.09441733364350127
epoch 40 | Loss: 0.02052626479496318
epoch 40 | Loss: 0.027745174324756906
epoch 40 | Loss: 0.02775144045831802
epoch 40 | Loss: 0.030536002208338534
epoch 40 | Loss: 0.03110053083599192
epoch 50 | Loss: 0.00662591983917979
epoch 50 | Loss: 0.008959274318573893
epoch 50 | Loss: 0.008961197606

17.99692772369434

In [144]:
# now we're going to do the same as tensorflow/pytorch

In [145]:
import tensorflow as tf

In [146]:
import numpy as np

In [147]:
input=[1,2,3,4,5,6,7,8]

In [148]:
output=[1,4,6,8,10,12,14,16]

In [149]:
x=np.array(input,dtype=float)

In [150]:
y=np.array(output,dtype=float)

In [180]:
model=tf.keras.Sequential([tf.keras.layers.Dense(30,activation='linear',input_shape=[1]),
                     tf.keras.layers.Dense(1)])  #this is just the architecture creation



In [181]:
model.compile(optimizer=tf.keras.optimizers.SGD(learning_rate=0.001),loss='mean_squared_error')

In [182]:
model.fit(x,y,epochs=100,verbose=1)



Epoch 1/100


ValueError: Exception encountered when calling Sequential.call().

Invalid input shape for input Tensor("data:0", shape=(None, 3, 4), dtype=float32). Expected shape (None, 1), but input has incompatible shape (None, 3, 4)

Arguments received by Sequential.call():
  • inputs=tf.Tensor(shape=(None, 3, 4), dtype=float32)
  • training=True
  • mask=None

In [163]:
x_input = np.array([[9]])  # shape (1, 1)
prediction = model.predict(x_input)
print(prediction)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 62ms/step
[[17.823065]]


In [164]:
data='help'

In [165]:
char2idx={'h':0,'e':1,'l':2,'p':3}

In [166]:
idxtoxhar={v:k for k,v in char2idx.items()}

In [167]:
idxtoxhar

{0: 'h', 1: 'e', 2: 'l', 3: 'p'}

In [171]:
input_seq = [char2idx[c] for c in data[:-1]]
target_seq=[char2idx[c] for c in data[1:]]

In [172]:
target_seq

[1, 2, 3]

In [174]:
x=tf.one_hot(input_seq,depth=4)
x=tf.expand_dims(x,axis=0)
y=tf.expand_dims(target_seq,axis=0)

In [175]:
x

<tf.Tensor: shape=(1, 3, 4), dtype=float32, numpy=
array([[[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.]]], dtype=float32)>

In [176]:
y

<tf.Tensor: shape=(1, 3), dtype=int32, numpy=array([[1, 2, 3]])>

In [183]:
model=tf.keras.Sequential([tf.keras.layers.LSTM(8,return_sequences=True, input_shape=(3,4)),
                     tf.keras.layers.Dense(4,activation='linear')])

C:\Users\HP\AppData\Roaming\Python\Python312\site-packages\keras\src\layers\rnn\rnn.py:204: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


In [185]:
model.compile(optimizer='adam',loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True))

In [188]:
for epoch in range(201):
    model.train_on_batch(x,y)
    
    if epoch % 50 ==0:
        output=model(x)
        print(output)
        pred=tf.argmax(output,axis=-1).numpy()[0]
        pred_char="".join([idxtoxhar[i] for i in pred])
        print(f"epoch: {epoch}, prediction: {pred_char}, loss:{loss}")

tf.Tensor(
[[[-0.53645873  0.73876595  0.25774828 -0.30751133]
  [-1.4413244  -0.192503    1.2563277   0.1151332 ]
  [-1.7203557  -1.0149704   0.52113056  2.1453185 ]]], shape=(1, 3, 4), dtype=float32)
epoch: 0, prediction: elp, loss:5.823832244906861e-07
tf.Tensor(
[[[-0.6539227   1.0225192   0.25680536 -0.53429466]
  [-1.7085444  -0.17389193  1.7319665  -0.06218081]
  [-1.7527261  -1.206457    0.5067114   2.7011714 ]]], shape=(1, 3, 4), dtype=float32)
epoch: 50, prediction: elp, loss:5.823832244906861e-07
tf.Tensor(
[[[-0.7657511   1.2974819   0.20653388 -0.7319976 ]
  [-1.9145019  -0.15759906  2.1666298  -0.24616948]
  [-1.6242427  -1.2966118   0.43755656  3.1594195 ]]], shape=(1, 3, 4), dtype=float32)
epoch: 100, prediction: elp, loss:5.823832244906861e-07
tf.Tensor(
[[[-0.86828285  1.5479963   0.12892698 -0.89299375]
  [-2.0713167  -0.14072403  2.526301   -0.40746352]
  [-1.4864782  -1.3768334   0.3711684   3.4968095 ]]], shape=(1, 3, 4), dtype=float32)
epoch: 150, prediction: elp